### ISSUE TITLE
Opacity info is wrong after start of the program

### ISSUE THREAD

**Issue by r4p7or** [andrijac/ruler#10]
Ruler 1.4.0.0
MD5 of Ruler.exe: d4698c417d853cee113335e20787a54d
Windows 7 64bit

Hi, thanks for improving this handy tool.
I have found a small bug.
When you start the Ruler it is partially transparent, but when you look at the Opacity submenu it says 100 %. It is not a big deal, just a little bit confusing (for new users). If you then click the 100 % option the ruler becomes fully opaque (which is OK).

![ruler_opacity_bug](https://user-images.githubusercontent.com/26348847/31052615-d1499b30-a689-11e7-8a0b-935248757614.png)

**Comment by andrijac** [comment]
I'll look into it

**Comment by andrijac** [comment]
It was already fixed in code, binaries are now updated too.
Check latest binary in Bin folder
https://github.com/andrijac/ruler/tree/master/Bin/1.4.1.0
