### ISSUE TITLE
Duplicating vertical ruler creates wider ruler

### ISSUE THREAD

**Issue by IsaacMorris1980** [andrijac/ruler#17]
When duplicating a vertical ruler, the duplicate ruler's width is almost 2 times as wide as original ruler.
issue also occurs in my pull request
Using build 1.4.5.0 
Windows 10 Insider build 17063

**Comment by IsaacMorris1980** [comment]
@andrijac  checking into this not sure why this is happening

**Comment by IsaacMorris1980** [comment]
@andrijac  when duplicate ruler is created on a vertical ruler it is adding about 56% more to width(eg. 75 width to 135) i do not yet know where the width is being changed.  it is correct when it is in the duplicatehandler function but the next time it is in the init(ruler rulerinfo)  function the width is 135

**Comment by IsaacMorris1980** [comment]
i am unable to start a vertical ruler or duplicating a vertical ruler with a width less then 136 if i do it resizes the width to 136, 

Note: after ruler displays at 136 it's width can be changed to be less then 136 and have no issues unless you duplicate that ruler

**Comment by andrijac** [comment]
Good find. I'll look into it. Thanks.
