### ISSUE TITLE
Context menu is not correctly duplicated

### ISSUE THREAD

**Issue by IsaacMorris1980** [andrijac/ruler#19]
When duplicating a ruler the context menu does not copy correctly, if items are checked in original the setting is still held in duplicate however unchecked in duplicate ruler context menu 

Version: 1.4.5.0
Window 10 insider build 17074

**Comment by IsaacMorris1980** [comment]
@andrijac  checking into this as well

**Comment by andrijac** [comment]
Good find. I'll look into this too. Thanks.

**Comment by andrijac** [comment]
Fixed in https://github.com/andrijac/ruler/commit/8308c435cb04084e7cc12d730f44ffe6df263da3
