### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by ciband** [andrijac/ruler#20]
It would be nice if the program would save its settings on exit so you don't have to re-enable tool tips, always on top, etc..

**Comment by andrijac** [comment]
I'm considering to review existing default settings and changing them a bit, as you mentioned: always-on-top and tool-tips should be enabled.

I'm trying to avoid saving state of ruler automatically or by user action to keep program simple. Ruler is made so you can run multiple instances on screen if you need to. Maybe you want to different sides of element on your screen, of measure multiple elements: some vertical, some horizontal. Each instance might have different settings at the moment and saving automatically (on closing) will be confusing. State of ruler will constantly change and there is too few settings to save anyway.

If you want specific settings for ruler, I suggest opening a ruler  with specific command line arguments, described in README.
