### ISSUE TITLE
Onmouse Down, Up and Move do not fire

### ISSUE THREAD

**Issue by IsaacMorris1980** [andrijac/ruler#26]
OnMouseDown, OnMouseUp and OnMouseMove  appearantly do not fire, i put break points in each and they were not hit the break points were on the first item in each, not sure what is happening

**Comment by andrijac** [comment]
It works for me.
Make sure you have Debug build configuration selected.
Does your breakpoint have question mark?

**Comment by IsaacMorris1980** [comment]
they say they will never be hit i will try it again

**Comment by andrijac** [comment]
It means that the code you are seeing does not correspond with binary you are running.
Make sure you have Debug build config selected, Clean solution, Rebuild solution.
Try some of the solutions from answers here:
https://stackoverflow.com/questions/2155930/how-do-i-remedy-the-the-breakpoint-will-not-currently-be-hit-no-symbols-have-b

**Comment by IsaacMorris1980** [comment]
@andrijac  i thing this might have been caused by my newer heavy handed firewall(most apps that i have installed were affected), i have since uninstalled the firewall and will attempt again

**Comment by IsaacMorris1980** [comment]
@andrijac  issue was some how my firewall issue no longer occurs
