### ISSUE TITLE
Centimeters

### ISSUE THREAD

**Issue by fpohtmeh** [andrijac/ruler#33]
Add ability to switch to centimenters for the metric world.

**Comment by IsaacMorris1980** [comment]
@fpohtmeh  do you mean convert from pixels to inches, milimeters, and centimeters?

**Comment by IsaacMorris1980** [comment]
@andrijac  i can try this one if this request is ok for the project

**Comment by andrijac** [comment]
I don't see the point of doing this. This is pixel ruler. If you wish to try, go ahead.

**Comment by CaelanStewart** [comment]
The results wouldn't make because you don't know the true DPI of the connected monitor, so if you use the system's DPI setting (usually 96 by default), the reported size will be completely wrong.

**Comment by IsaacMorris1980** [comment]
@andrijac  i am able to do this but when converting to inches / centimeters/ millimeters there is some rounding issues that would occur so it would not be as accurate as the pixel ruler it is currently how would you like me to proceed

**Comment by IsaacMorris1980** [comment]
@andrijac  while checking into it further the system defaults 100% to 96 dpi(even though my monitor should be defaulted higher) and when increasing eg. 125-175 just increases its number based on 96 so even if your monitor was a 300 dpi monitor unless it was somehow reporting correctly the resulting conversions would not be accurate.
