### ISSUE TITLE
Bug: If window is moved too quickly, it doesn't move

### ISSUE THREAD

**Issue by CaelanStewart** [andrijac/ruler#35]
If you drag and drop the ruler above a certain speed, the move is not registered and the cursor begins to move independently of the ruler. It seems that it happens when you move the cursor at a speed high enough such that by the time the new position of the cursor is registered and sent to the ruler app, the cursor is no longer within the bounds of the ruler's draggable area.

Windows 10 x64 16299.371

**Comment by edgariscoding** [comment]
This has been happening for me as well.

**Comment by vadimhp** [comment]
Yeah. This bug is super annoying, happening very often, and productivity inhibiting. Wish I knew windows so I could pull request lol good luck!

**Comment by andrijac** [comment]
I'll look it up.

**Comment by andrijac** [comment]
When my cursor "falls off" Ruler while dragging, I can still go back, click and hold on Ruler and continue dragging. This is known bug and I have no idea why is this happening. I think it is related to Windows Forms GUI behavior.
