### ISSUE TITLE
Request: Resize from top/left sides

### ISSUE THREAD

**Issue by CaelanStewart** [andrijac/ruler#36]
It would be nice if you could resize the window from the left and top sides, rather than just the bottom/right sides of the window.

**Comment by andrijac** [comment]
I think we had this issue before, I'll look it up.

**Comment by IsaacMorris1980** [comment]
@andrijac   I believe this is similar to #2

**Comment by alexis-m** [comment]
I am working on this. I don't see how to assign this issue to myself, though. 😄
