### ISSUE TITLE
Change icon?

### ISSUE THREAD

**Issue by ben-burlingham** [andrijac/ruler#40]
Hi everyone, this ruler is great - it does exactly what it says, it's easy to use, it's fast.

I just have one complaint: I use it at work, and have it pinned in taskbars, and the icon gets a lot of questions.  

Can you change the icon to something that represents this wonderful app a little better?  I'm happy to contribute one/some if you like.  Thanks!

**Comment by andrijac** [comment]
Sure, if you have better icon, please recommend it.
The only reason I'm using current icon is out of respect to original author, but I don't mind changing it.

**Comment by ben-burlingham** [comment]
Just riffing a little bit, do you like one of or a combination of one of these designs?  If so, I'll flesh it out and make an `.ico` file with the various sizes.

#### Icon 1
![icon1](https://user-images.githubusercontent.com/6643933/40880953-c2494bac-666f-11e8-9b09-272fe2a2b892.png)

#### Icon 2
![icon2](https://user-images.githubusercontent.com/6643933/40880954-c26dd2c4-666f-11e8-887c-68e710eef74f.png)

#### Icon 3
![icon3](https://user-images.githubusercontent.com/6643933/40880955-c28570e6-666f-11e8-85a3-20cc16ce981e.png)

**Comment by ben-burlingham** [comment]
@andrijac I guess you're not too into these? :)

**Comment by leglock** [comment]
I would be happy to implement this change if we can find a icon everyone likes. I personally think icon 3 provided by @ben-burlingham looks nice. 

@andrijac do you have a thought on this?

**Comment by jnslmk** [comment]
I also like icon 3. Maybe make it diagonal in a 45° angle?

**Comment by ben-burlingham** [comment]
At work (source file is at home) but here's rotated samples: 

#### A 
![ruler1](https://user-images.githubusercontent.com/6643933/50779291-cc8f3180-1254-11e9-9ea9-66600b898943.png)

#### B 
![ruler2](https://user-images.githubusercontent.com/6643933/50779292-cd27c800-1254-11e9-80a4-fe9d518b3357.png)

**Comment by jnslmk** [comment]
I like option B.

Also the simplicity fits the aim of the program.

**Comment by ben-burlingham** [comment]
Good point!

Cool, just let me know when to pull the trigger and I'll provide an `.ico` file.  Might wait for another opinion or two just to be on the safe side :)

**Comment by leglock** [comment]
I like B as well. If you want to go ahead and post the icon, I will make the change and @andrijac can reject the pull request if he doesn't care for it.

**Comment by ben-burlingham** [comment]
@leglock All set. Github doesn't support `.ico` filetypes (or source file types for Gimp or Photoshop) so I emailed you the file to the email posted in your account.  Happy to make the PR myself if granted push access.

**Comment by andrijac** [comment]
How about yellow rotated 45°?
I like yellow because it will stand out.

**Comment by alexis-m** [comment]
I like yellow 45 degrees. Although it's going to remind me of another ruler I had been using for years in the past. http://www.spadixbd.com/freetools/jruler.htm

It stopped working with Windows 10, so I had to find a replacement. This is how I found this open-source ruler. :grin:

**Comment by andrijac** [comment]
@alexis-m maybe that's a good thing :) we will step into old ruler's place.

**Comment by ben-burlingham** [comment]
:) Happy to add the yellow 45 too.  But since I can't attach `.ico` here, if I can get push access, I can make PRs so people can see the two options.

**Comment by ben-burlingham** [comment]
Hmm, I'll try again later, but I thought to push the branch to create the PR from, I'll need access.  Maybe I've been working on restricted repos for too long 😅

**Comment by andrijac** [comment]
Damn, now when I think of it, we will have 45 angle ruler icon, and our ruler will not be able to do the same. I'm not so sure right now...

**Comment by andrijac** [comment]
How about horizontal yellow ruler icon? What do ya'll thing?

**Comment by andrijac** [comment]
Fact is, current icon needs to be replaced one way or another.

**Comment by alexis-m** [comment]
We can totally start with a yellow horizontal ruler.

**Comment by ben-burlingham** [comment]
PR created: https://github.com/andrijac/ruler/pull/49
