### ISSUE TITLE
Constrain user movement axis with Shift

### ISSUE THREAD

**Issue by jnslmk** [andrijac/ruler#42]
To put elements on screen in relation more easily, I propose the feature to constrain the rulter movement with the **Shift** key.
Dragging the ruler with the mouse while holding **Shift** would allow the ruler to move either up and down or left and right.

Powerpoint and other Microsoft products implements this feature with **Shift**.
Inkscape uses the **Ctrl** key instead.
I believe there are more programs offering a similar feature.

**Comment by alexis-m** [comment]
I will work on this after #36.
