### ISSUE TITLE
Ruler resizes if moved too quickly

### ISSUE THREAD

**Issue by mwaltersva** [andrijac/ruler#5]
When moving the ruler (via clicking inside the ruler and dragging it), it will resize if the mouse is moved "too quickly".

To replicate: left click and hold in the middle, then rapidly move the mouse, the ruler will begin to resize.

My system: Windows 10 v1607 build 14393.187, 64bit.

This occurred with the pre-built binary in bin/debug

**Comment by andrijac** [comment]
I know about this issue. It's like mouse detaches away from drag point. I think this is due to fact that ruler is built with Windows Forms library and it's a problem on .NET level. I'm not sure if we can do anything about it. I got used to it over years using it and just drag it slower. I'll check if there is anything I can do about it when I find time, but can't promise anything.

**Comment by andrijac** [comment]
I'll try to look what FDIM did with this issue.

**Comment by IsaacMorris1980** [comment]
@andrijac  to fix this issue i created a variable called previously locked, and set it during init and when islocked is changed to true and turned off if islocked was set to false,  Then in the mouse down, mouse up this variable is checked to see about turning off islocked, in the mouse move event after determining that the mouse in not in the border you lock resize.  If you would like i could create a pr for just that feature.

**Comment by andrijac** [comment]
I see what you are saying now. I haven't tried that use case when I was trying your PR.
I'm doing little bit of refactoring of code in MainForm and moving code around, it would be good to wait for me to finish on master, it won't take long.

**Comment by andrijac** [comment]
@IsaacMorris1980 you can make a PR now

**Comment by IsaacMorris1980** [comment]
@andrijac checking out your refactoring of code to make sure fix still works and meets all contributing guidelines

**Comment by IsaacMorris1980** [comment]
@andrijac  unable to test as #26  occurs so i can not test if fix variable ever changes
