### ISSUE TITLE
Saving location?

### ISSUE THREAD

**Issue by oryxcallotis** [andrijac/ruler#57]
This is a great little program, but is it possible to save the location & size for future use?

**Comment by andrijac** [comment]
One issue here, problem is if you are switching monitors, or number of monitors, Ruler will not be visible if it ends up off screen.
We should implement location setting from command line, location should be part of "Copy Ruler Info".

**Comment by IsaacMorris1980** [comment]
@andrijac Should the app enumerate which monitor it is on and if the monitor is not there(when relaunched) fall back to monitor 1 at location on 3rd monitor?

**Comment by andrijac** [comment]
@IsaacMorris1980 switching monitors example: if you using laptop with docking station that is connected to 2 other monitors. There will be difference on and off docking station.

We can implement this behavior but it should be optional. Also, I would separate option to save location and size.

Location restore needs to check if it's visible on screen and size restore needs to check if it fits the screen. If not, fallback to defaults.

**Comment by IsaacMorris1980** [comment]
Is it ok if i try this one ?

**Comment by IsaacMorris1980** [comment]
@andrijac   on my branch [Saving Locaton](https://github.com/IsaacMorris1980/ruler/tree/Saving_locaton) i think i have this implemented(non-optional) .  Now have to make it optional, but i dont have the multiple monitors to test that part with.

**Comment by andrijac** [comment]
Before Form is shown, in debugger, try setting the Location of Form outside your screen, giving it very large number for location.

**Comment by IsaacMorris1980** [comment]
Will do,  still working on making it optional, should have a PR soon

**Comment by IsaacMorris1980** [comment]
Should have a PR soon not sure why when i only added a few items in pr it is like i am replacing it all.  I am also adding screen check though i had it but on new branch i forgot to implement screen check.  Sorry would have like to put a PR in today

**Comment by IsaacMorris1980** [comment]
will have a new pr with this implemented without creating new files in a little while trying to optimze my code

**Comment by IsaacMorris1980** [comment]
Implemented in Build 2.0.1.0
