### ISSUE TITLE
Values are incorrect if display scaling not set to 100%

### ISSUE THREAD

**Issue by sba923** [andrijac/ruler#68]
My old eyes need to set display scaling to 125%

This results in Ruler 2.0 giving incorrect values:

![vlcsnap-2024-01-20-08h02m38s972](https://github.com/andrijac/ruler/assets/12860484/bc136a25-1278-47ff-80c4-422961965414)
![vlcsnap-2024-01-20-08h03m06s132](https://github.com/andrijac/ruler/assets/12860484/cac3dc17-1b6d-4b77-815f-0e9fa917765e)

**Comment by IsaacMorris1980** [comment]
possibly related to #54

**Comment by IsaacMorris1980** [comment]
Investigating along with #54

**Comment by IsaacMorris1980** [comment]
@sba923  When a beta build is ready would you be able to test?

**Comment by sba923** [comment]
> @sba923  When a beta build is ready would you be able to test?

Sure!

**Comment by IsaacMorris1980** [comment]
@sba923   here is a link to a beta build not sure if it is fixed i think it is

https://github.com/IsaacMorris1980/ruler/releases/tag/Beta2.0.2

**Comment by sba923** [comment]
This seems to be OK: the beta build does report that my monitor is 1920x1080 pixels (1923x1081 actually but this might be a positioning error of the top-left Ruler corner...).

**Comment by IsaacMorris1980** [comment]
hmmm, i will look into it.  do you want me to close this one and open a new one for incorrect pixel dimensions?

**Comment by sba923** [comment]
Not at this point. I will first check against a rectangle of known dimensions, for instance measured with PowerToys Screen Ruler.

**Comment by sba923** [comment]
Seems to be OK. If I force the size to 1800x300, PowerToys Screen Ruler measures the inside of the Ruler to be 1798 pixels, which should be OK assuming that the outside rectangle's vertical borders are one pixel wide.

**Comment by IsaacMorris1980** [comment]
i believe so but i will take a look

**Comment by IsaacMorris1980** [comment]
@sba923   the border is 1 pixel wide the rectangle is drawn  width-1 and height -1

**Comment by IsaacMorris1980** [comment]
merging and creating release build

**Comment by IsaacMorris1980** [comment]
Issue is resolved in build 2.0.2.0
https://github.com/andrijac/ruler/releases/tag/2.0.2.0
