### ISSUE TITLE
standalone application  not loading local settings file on windows 11

### ISSUE THREAD

**Issue by IsaacMorris1980** [andrijac/ruler#69]
When the application has the saved user settings it is looking for settings file in appdata file instead of local folder where application was run from on windows 11

**Comment by andrijac** [comment]
I don't remember saving any user settings locally. Maybe you are talking about some fork?

**Comment by IsaacMorris1980** [comment]
it is the save location branch is failing but had been working locally for me

**Comment by IsaacMorris1980** [comment]
issue has been resolved
