### ISSUE TITLE
Double-click to change orientation

### ISSUE THREAD

**Issue by RrnR** [andrijac/ruler#7]
Double-click doesn't seem to be assigned to anything, and this seems like the obvious choice - it's the most common operation, and it would ease migration from my last tool. ;-)

**Comment by leglock** [comment]
I am going to give this one a crack this evening.

**Comment by joce** [comment]
If you wish to take my branch, I have implemented that... and a whole lot more.

**Comment by andrijac** [comment]
Implemented in 1.4.2.0.

BTW, 'Space' key also changes orientation.
